const AuthConstants = {
  AUTH_CALLBACK_ERROR: 'AUTH_CALLBACK_ERROR',
  AUTH_CALLBACK_SUCCESS: 'AUTH_CALLBACK_SUCCESS',
  AUTH_CALLBACK_LOGOUT: 'AUTH_CALLBACK_LOGOUT',
};

export default AuthConstants;
